### ISSUE TITLE
[Feature] 有的用户注册表的QQ路径和实际QQ不一致导致的情况能否让用户手动输入路径

### ISSUE THREAD

**Issue by linyuchen** [super1207/install_llob#1]
https://github.com/super1207/install_llob/blob/c241e7308f5007896821e08288223ec5a090f8cc/src/main.rs#L10

注册表的路径是 QQ 安装时添加的，如果用户手动移动了QQ目录或者使用绿色版之类的则无法找到 QQ.exe

当找不到路径时能否提示用户手动拖入QQ.exe到cmd来识别到QQ安装路径

**Comment by super1207** [comment]
支持了
