### ISSUE TITLE
"Failed to get tag_name"

### ISSUE THREAD

**Issue by Xuan-Xuann** [super1207/install_llob#12]
2024-08-10 22:02:45  INFO llob_install: 正在获取最新QQNTFileVerifyPatch版本号...
2024-08-10 22:02:45 ERROR llob_install: "Failed to get tag_name"
 
开发者您好，当我运行这个exe文件时，到这一步直接卡住了，希望您能帮我解决下，谢谢

**Comment by super1207** [comment]
你在你的浏览器里面尝试访问下这个地址，看看显示什么：https://api.github.com/repos/LiteLoaderQQNT/QQNTFileVerifyPatch/releases/latest

**Comment by Xuan-Xuann** [comment]
{
    "url": "https://api.github.com/repos/LiteLoaderQQNT/QQNTFileVerifyPatch/releases/167950494",
    "assets_url": "https://api.github.com/repos/LiteLoaderQQNT/QQNTFileVerifyPatch/releases/167950494/assets",
    "upload_url": "https://uploads.github.com/repos/LiteLoaderQQNT/QQNTFileVerifyPatch/releases/167950494/assets{?name,label}",
    "html_url": "https://github.com/LiteLoaderQQNT/QQNTFileVerifyPatch/releases/tag/DllHijack_1.1.0",
    "id": 167950494,
    "author": {
        "login": "sysrom",
        "id": 88297660,
        "node_id": "MDQ6VXNlcjg4Mjk3NjYw",
        "avatar_url": "https://avatars.githubusercontent.com/u/88297660?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/sysrom",
        "html_url": "https://github.com/sysrom",
        "followers_url": "https://api.github.com/users/sysrom/followers",
        "following_url": "https://api.github.com/users/sysrom/following{/other_user}",
        "gists_url": "https://api.github.com/users/sysrom/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/sysrom/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/sysrom/subscriptions",
        "organizations_url": "https://api.github.com/users/sysrom/orgs",
        "repos_url": "https://api.github.com/users/sysrom/repos",
        "events_url": "https://api.github.com/users/sysrom/events{/privacy}",
        "received_events_url": "https://api.github.com/users/sysrom/received_events",
        "type": "User",
        "site_admin": false
    },
    "node_id": "RE_kwDOK4_YR84KArie",
    "tag_name": "DllHijack_1.1.0",
    "target_commitish": "DLLHijackMethod",
    "name": "DllHijack_1.1.0",
    "draft": false,
    "prerelease": false,
    "created_at": "2024-07-31T00:42:55Z",
    "published_at": "2024-07-31T00:52:46Z",
    "assets": [
        {
            "url": "https://api.github.com/repos/LiteLoaderQQNT/QQNTFileVerifyPatch/releases/assets/182871632",
            "id": 182871632,
            "node_id": "RA_kwDOK4_YR84K5mZQ",
            "name": "dbghelp_arm64.dll",
            "label": null,
            "uploader": {
                "login": "sysrom",
                "id": 88297660,
                "node_id": "MDQ6VXNlcjg4Mjk3NjYw",
                "avatar_url": "https://avatars.githubusercontent.com/u/88297660?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/sysrom",
                "html_url": "https://github.com/sysrom",
                "followers_url": "https://api.github.com/users/sysrom/followers",
                "following_url": "https://api.github.com/users/sysrom/following{/other_user}",
                "gists_url": "https://api.github.com/users/sysrom/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/sysrom/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/sysrom/subscriptions",
                "organizations_url": "https://api.github.com/users/sysrom/orgs",
                "repos_url": "https://api.github.com/users/sysrom/repos",
                "events_url": "https://api.github.com/users/sysrom/events{/privacy}",
                "received_events_url": "https://api.github.com/users/sysrom/received_events",
                "type": "User",
                "site_admin": false
            },
            "content_type": "application/x-msdownload",
            "state": "uploaded",
            "size": 357888,
            "download_count": 198,
            "created_at": "2024-07-31T00:47:47Z",
            "updated_at": "2024-07-31T00:47:48Z",
            "browser_download_url": "https://github.com/LiteLoaderQQNT/QQNTFileVerifyPatch/releases/download/DllHijack_1.1.0/dbghelp_arm64.dll"
        },
        {
            "url": "https://api.github.com/repos/LiteLoaderQQNT/QQNTFileVerifyPatch/releases/assets/182871664",
            "id": 182871664,
            "node_id": "RA_kwDOK4_YR84K5mZw",
            "name": "dbghelp_x64.dll",
            "label": null,
            "uploader": {
                "login": "sysrom",
                "id": 88297660,
                "node_id": "MDQ6VXNlcjg4Mjk3NjYw",
                "avatar_url": "https://avatars.githubusercontent.com/u/88297660?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/sysrom",
                "html_url": "https://github.com/sysrom",
                "followers_url": "https://api.github.com/users/sysrom/followers",
                "following_url": "https://api.github.com/users/sysrom/following{/other_user}",
                "gists_url": "https://api.github.com/users/sysrom/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/sysrom/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/sysrom/subscriptions",
                "organizations_url": "https://api.github.com/users/sysrom/orgs",
                "repos_url": "https://api.github.com/users/sysrom/repos",
                "events_url": "https://api.github.com/users/sysrom/events{/privacy}",
                "received_events_url": "https://api.github.com/users/sysrom/received_events",
                "type": "User",
                "site_admin": false
            },
            "content_type": "application/x-msdownload",
            "state": "uploaded",
            "size": 380928,
            "download_count": 5314,
            "created_at": "2024-07-31T00:47:55Z",
            "updated_at": "2024-07-31T00:47:55Z",
            "browser_download_url": "https://github.com/LiteLoaderQQNT/QQNTFileVerifyPatch/releases/download/DllHijack_1.1.0/dbghelp_x64.dll"
        },
        {
            "url": "https://api.github.com/repos/LiteLoaderQQNT/QQNTFileVerifyPatch/releases/assets/182871707",
            "id": 182871707,
            "node_id": "RA_kwDOK4_YR84K5mab",
            "name": "dbghelp_x86.dll",
            "label": null,
            "uploader": {
                "login": "sysrom",
                "id": 88297660,
                "node_id": "MDQ6VXNlcjg4Mjk3NjYw",
                "avatar_url": "https://avatars.githubusercontent.com/u/88297660?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/sysrom",
                "html_url": "https://github.com/sysrom",
                "followers_url": "https://api.github.com/users/sysrom/followers",
                "following_url": "https://api.github.com/users/sysrom/following{/other_user}",
                "gists_url": "https://api.github.com/users/sysrom/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/sysrom/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/sysrom/subscriptions",
                "organizations_url": "https://api.github.com/users/sysrom/orgs",
                "repos_url": "https://api.github.com/users/sysrom/repos",
                "events_url": "https://api.github.com/users/sysrom/events{/privacy}",
                "received_events_url": "https://api.github.com/users/sysrom/received_events",
                "type": "User",
                "site_admin": false
            },
            "content_type": "application/x-msdownload",
            "state": "uploaded",
            "size": 316928,
            "download_count": 283,
            "created_at": "2024-07-31T00:48:03Z",
            "updated_at": "2024-07-31T00:48:04Z",
            "browser_download_url": "https://github.com/LiteLoaderQQNT/QQNTFileVerifyPatch/releases/download/DllHijack_1.1.0/dbghelp_x86.dll"
        }
    ],
    "tarball_url": "https://api.github.com/repos/LiteLoaderQQNT/QQNTFileVerifyPatch/tarball/DllHijack_1.1.0",
    "zipball_url": "https://api.github.com/repos/LiteLoaderQQNT/QQNTFileVerifyPatch/zipball/DllHijack_1.1.0",
    "body": "添加ARM64支持\r\n<img src='https://i.postimg.cc/GTPSzqwc/suzume-bili-Ag-ADXg0-AAq7te-Vc.webp' border='0' alt='suzume-bili-Ag-ADXg0-AAq7te-Vc'/>",
    "reactions": {
        "url": "https://api.github.com/repos/LiteLoaderQQNT/QQNTFileVerifyPatch/releases/167950494/reactions",
        "total_count": 10,
        "+1": 10,
        "-1": 0,
        "laugh": 0,
        "hooray": 0,
        "confused": 0,
        "heart": 0,
        "rocket": 0,
        "eyes": 0
    }
}

**Comment by super1207** [comment]
应该是偶然的网络原因吧，下次更新我会在脚本里面重试几次，你也可以试试多运行几次。
![image](https://github.com/user-attachments/assets/4c2fbcf2-a648-4422-ab6b-31390a007ffc)

**Comment by Xuan-Xuann** [comment]
好的，十分感谢
