### ISSUE TITLE
qq最新版本没有问题，安装插件时出现未知错误

### ISSUE THREAD

**Issue by HMSXEF** [super1207/install_llob#5]
![Screenshot_20240705_091202_com.microsoft.rdc.androidx.jpg](https://github.com/super1207/install_llob/assets/141598320/0012f04b-8d76-4084-9136-5f37ab8a365c)

**Comment by super1207** [comment]
参考：
https://github.com/LLOneBot/LLOneBot/issues/253

**Comment by HMSXEF** [comment]
好的
