### ISSUE TITLE
安装时提示由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

### ISSUE THREAD

**Issue by lihuaxue** [super1207/install_llob#6]
![20411163d4040c267c0ec09fa1f13d41](https://github.com/user-attachments/assets/43a26af8-f8e8-4ec5-a72f-8fb0455942cd)

**Comment by super1207** [comment]
没办法解决，github api在大陆某些地区的确是被墙的状态。手动安装吧
